spring:
  application:
    name: loan-banking App


  datasource:
    url: jdbc:mysql://localhost:3306/john_bosco_db
    username: root
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Scheduler Configuration
  task:
    scheduling:
      pool:
        size: 10
