spring:
  application:
    name: loan-banking App

  datasource:
    url: jdbc:mysql://localhost:3306/loan_bank_app?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Scheduler Configuration
  task:
    scheduling:
      pool:
        size: 10

jwt:
  secret: "thisisacodingjustasdemonstrationforsecretkeyinspringsecurityjsonwebtokenauthentication"
  expiration: 3600000



path:
  logging: C:\\Logs\\loan_banking\\



springdoc:
  api-docs:
    path: /api-docs
